#!/bin/bash

cd ./outputs

rm ./tmp_animations/*

for i in {0..1240..20} 
do


file1='Hare'$i'.ppm'
file2='Puma'$i'.ppm'


if [ $i -lt 10 ]
then
ppmtogif $file1 > 'tmp_animations/Hare000'$i'.gif'
ppmtogif $file2 > 'tmp_animations/Puma000'$i'.gif'
elif [ $i -lt 100 ]
then
ppmtogif $file1 > 'tmp_animations/Hare00'$i'.gif'
ppmtogif $file2 > 'tmp_animations/Puma00'$i'.gif'
elif [ $i -lt 1000 ]
then
ppmtogif $file1 > 'tmp_animations/Hare0'$i'.gif'
ppmtogif $file2 > 'tmp_animations/Puma0'$i'.gif'
else
ppmtogif $file1 > 'tmp_animations/Hare'$i'.gif'
ppmtogif $file2 > 'tmp_animations/Puma'$i'.gif'
fi

done

cd ./tmp_animations

HARES=`ls Hare*`
PUMAS=`ls Puma*`

gifsicle --delay=50 --loop -i $HARES > anim_Hare.gif
gifsicle --delay=50 --loop -i $PUMAS > anim_Puma.gif

